CorpusBaseDir = '/Users/michael/development/silbido/corpora/paper_files/';
RelativeFilePath = 'common/Qx-Dd-SCI0608-Ziph-060817-100219.wav';
%NoiseBoundariesFile = 'sandbox/testing/cache/Qx-Tt-SCI0608-N1-060814-121518.changes.mat';
NoiseBoundariesFile = 'sandbox/testing/cache/common/Qx-Dd-SCI0608-Ziph-060817-100219.changes.mat';

load(NoiseBoundariesFile, 'noiseBoundaries');

SilbidoDebugUI(...
    [CorpusBaseDir, RelativeFilePath], ...
    'ViewStart', 0, ...
    'ViewLength', 7, ...
    'NoiseBoundaries', noiseBoundaries);